add-controllers
antbaranov/java-shareit pull request #1
Opened 2023-01-15 19:20 UTC by antbaranov

2023-01-15 19:58 UTC, antbaranov commented
Я не нашел правила копирования шаблона проект. Сделал, как и раньше: форкнул и склонировал

2023-01-15 20:01 UTC, antbaranov commented
Изначально в проекте я использовал для id обёртку Long, но тесты github не пропустили. Как правильно использовать в проекте Long или long ?

2023-01-16 13:10 UTC, AnastasiyaFomkina commented
> Изначально в проекте я использовал для id обёртку Long, но тесты github не пропустили. Как правильно использовать в проекте Long или long ?

Странно, что тесты не прошли. Можно и так и так, если нам не нужны методы обертки, то лучше использовать примитив, так как он в любом случае будет занимать меньше памяти и быстрее отрабатывать. 
Вот [здесь](https://topjava.ru/blog/primitives-and-referenses) можно почитать про разницу

2023-01-16 13:30 UTC, AnastasiyaFomkina requested changes
Отличная работа, молодец 👍 Оставила один комментарий для саморазвития, его можно выполнить, если будет время и желание

2023-01-16 13:30 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto create(@RequestHeader("X-Sharer-User-Id") long userId, @Valid @RequestBody ItemDto itemDto) {
Лучше вынести название хедера в константу, так как оно повторяется ниже несколько раз

2023-01-16 13:30 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
_Саморазвитие_
В коммерческой разработке принято максимально избавляться от шаблонного кода, чтобы не перегружать и так большие и объемные проекты. Для маппинга сущностей часто используется библиотека [Mapstruct](https://blog.skillfactory.ru/glossary/mapstruct/), которая позволяет автоматически настраивать маппинг из одной сущности в другую с помощью описания интерфейсов и аннотаций.
Вот [здесь](https://www.baeldung.com/mapstruct) есть отличный гайд для старта работы с библиотекой. 
При наличии свободного времени можно поизучать и попробовать прикрутить в проект

2023-01-16 13:30 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        boolean flag = users.stream()
Можно сразу возвращать результат операции, так как дальше эта переменная больше нигде не используется:
```suggestion
        return users.stream()
                .anyMatch(repoUser -> repoUser.getEmail().equals(email));
```

2023-01-16 13:34 UTC, antbaranov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto create(@RequestHeader("X-Sharer-User-Id") long userId, @Valid @RequestBody ItemDto itemDto) {
Я пробовал не получилось. Тесты не пропускают с константой

2023-01-17 10:25 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto create(@RequestHeader("X-Sharer-User-Id") long userId, @Valid @RequestBody ItemDto itemDto) {
Окей

2023-01-17 10:27 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto create(@RequestHeader("X-Sharer-User-Id") long userId, @Valid @RequestBody ItemDto itemDto) {
<img width="565" alt="Снимок экрана 2023-01-17 в 13 25 54" src="https://user-images.githubusercontent.com/43168217/212874599-e90c6b5f-36a0-4c4e-9da9-90445950ff43.png">
Тут могла быть проблема так как в константе лишние кавычки, должно быть:
`private final String X_SHARER_USER_ID = "X-Sharer-User-Id";`
 Так как это обычная строка :)

2023-01-17 10:29 UTC, AnastasiyaFomkina approved these changes
Молодец, что изучил mapstruct 🔥

2023-01-25 16:17 UTC, merged