Add bookings
antbaranov/java-shareit pull request #2
Opened 2023-01-28 06:46 UTC by antbaranov

2023-01-28 20:24 UTC, AnastasiyaFomkina requested changes
Оставлю тут общие комментарии по работе:

- Лучше стараться максимально декомпозировать большие методы на более мелкие логические состовляющие, так код будет проще читать и тестировать в дальнейшем

- Нужно максимально разнести классы по пакетам, например, создать для комментариев отдельный подпакет в пакете item и так далее. Можно отталкиваться от пакета booking, но и к нему нужно добавить дополнительный подпакет для сервисов

2023-01-28 20:24 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/exception/BookingNotFoundException.java
> +public class BookingNotFoundException extends Exception {
Исключения должны быть непроверяемыми, следует наследовать этот класс от `RuntimeException`. Так же следует исключить его из заголовков всех методов, так как непроверяемые исключения не нужно в них указывать)

2023-01-28 20:24 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/exception/ErrorResponse.java
> +    public String getError() {
Лучше генерировать геттер и конструктор с помощью lombok

2023-01-28 20:24 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    public static BookingInfoDto toBookingInfoDto(Booking booking) {
_Саморазвитие_
И снова предложу изучить библиотечку [Mapstruct](https://blog.skillfactory.ru/glossary/mapstruct/)
С ней процесс маппинга становится гораздо проще и быстрее реализовать
Вот [здесь](https://www.baeldung.com/mapstruct) есть отличный гайд для старта работы с библиотекой.
При наличии свободного времени можно поизучать и попробовать прикрутить в проект

2023-01-28 20:24 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@ToString
Перед использованием аннотаций автоматической генерации кода по типу `@ToString` над классами-сущностями - хорошо было бы ознакомиться с этой статьей:
https://habr.com/ru/company/haulmont/blog/564682/

2023-01-28 20:24 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +    public List<Comment> findAllByItem_Id(Long itemId);
модификатор `public` лишний, так как все методы интерфейса по дефолту - `public`

2023-01-28 20:24 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public static ItemInfoDto toItemInfoDto(Item item) {
метод нигде не используется, лучше удалить

2023-01-28 20:24 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findAllByOwner_Id(Long userId);
Лучше не использовать нижнее подчеркивание в именованиях джава-методов, это не соответствует code-style.
Поправь, пожалуйста, по всему проекту

2023-01-28 20:24 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        itemDto.setLastBooking(lastBooking.isEmpty() ? null : LastBookingDto.builder()
Можно заменить на выражение в функциональном стиле:
```suggestion
        itemDto.setLastBooking(lastBooking.map(booking -> LastBookingDto.builder()

2023-01-28 20:24 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        for (Item item : searchItems) {
Нужно реализовать с помощью стрима или `forEach()`

2023-01-28 20:24 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public List<ItemDto> get(Long userId) throws UserNotFoundException {
Все большие методы лучше декомпозировать на более мелкие по логическому принципу. 
Например, можно вынести работу с комментариями в отдельный service

2023-01-28 20:24 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            itemDto.setLastBooking(lastBooking.isEmpty() ? LastBookingDto.builder().build() : LastBookingDto.builder()
Лучше вынести в отдельный класс маппер

2023-01-28 20:24 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (!repoItem.getOwner().getId().equals(owner.getId())) throw new ItemNotFoundException("item not found");
Весь блок кода после условий, даже однострочный принято выделять в фигурные скобки `{}`. Так код становится более структурированным и его проще читать.
Поправь, пожалуйста, по всему проекту

2023-01-28 20:24 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            Sort sortAsc = Sort.by(Sort.Direction.ASC, "end");
Можно вынести в константу, повторяется несколько раз

2023-01-28 20:24 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            if (itemDto.getLastBooking().getBookerId() == null) {
И здесь тоже

2023-01-28 20:24 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        itemDto.setNextBooking(nextBooking.isEmpty() ? null : NextBookingDto.builder()
И здесь тоже

2023-01-28 20:24 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private State validateState(String value) throws InvalidStatusException {
Лучше перенести метод в `enum State` и сделать статическим, а этот удалить. 
Плюс метод `valueOf` выбрасывает два вида исключений: `IllegalArgumentException`, если не найден соответствующий элемент или `NullPointerException`, если элемент или название `null`, поэтому преобразовывать все ошибки к `IllegalArgumentException` не имеет смысла. Лучше выбрасывать свою бизнес ошибку, если нам нужно сообщить, что мы не нашли нужный нам `enum`

2023-01-28 20:24 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/ErrorHandler.java
> +    public ErrorResponse handleInvalidStatusException(InvalidStatusException e) {
Лучше не использовать однобуквенные названия переменных

2023-01-28 20:24 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!userId.equals(item.getOwner().getId()) && !userId.equals(booking.getBooker().getId())) {
Повторяющиеся условия
 лучше выносить в отдельный метод, например:
```
private boolean isUserIsOwner(Long userId, Item item) {
        return !userId.equals(item.getOwner().getId());
    }
```

2023-01-28 20:24 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            state = State.valueOf(value);
Лучше сразу возвращать результат: 
```suggestion
            return State.valueOf(value);
```
Тогда не нужно будет вводить переменную `state`

2023-01-29 05:41 UTC, antbaranov commented on src/main/java/ru/practicum/shareit/booking/exception/BookingNotFoundException.java
> +public class BookingNotFoundException extends Exception {
> так же следует исключить его из заголовков всех методов, так как непроверяемые исключения не нужно в них указывать)

Это не понял

2023-01-29 12:55 UTC, antbaranov commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    public static BookingInfoDto toBookingInfoDto(Booking booking) {
Попробовал, получилось только для UserMapper

2023-01-29 12:55 UTC, antbaranov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        itemDto.setLastBooking(lastBooking.isEmpty() ? null : LastBookingDto.builder()
Пробовал, не работает

2023-01-30 12:52 UTC, AnastasiyaFomkina requested changes
Не все кастомные ошибки наследуются от `RuntimeException`, нужно поправить

2023-01-30 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/dto/State.java
> +        State state = State.ALL;
Переменная нигде не используется, нужно удалить

2023-01-30 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    Sort SORT = Sort.by(Sort.Direction.DESC, "start");
Для обозначения константного значения нужно добавить модификатор доступа + сочетание ключевых слов `static final`

2023-01-30 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/__ErrorHandler.java
> +public class __ErrorHandler {
Некорректное название класса

2023-01-30 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/NotAvailableException.java
> +public class NotAvailableException extends Exception {
Нигде не используется - нужно удалить

2023-01-30 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/comment/service/CommentServiceImpl.java
> +            throws ItemNotFoundException, UserNotFoundException, InvalidCommentException {
Так как все типы приведенных здесь ошибок являются теперь непроверяемыми, обрабатывать их больше ненужно. Нужно удалить строку с `throws`

2023-01-30 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    Sort SORT_DESC = Sort.by(Sort.Direction.DESC, "end");
Строки 38-39 должны быть константами

2023-01-30 12:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Comment> commentList = commentRepository.findAllByItem_Id(itemId);
Код со строк 82-86 нужно вынести в отдельный метод в `CommentServiceImpl` и использовать его. Ниже на строках 126-130 он дублируется. Если передавать в параметрах метода `Long itemId`, то можно будет переиспользовать его, а не дублировать один и тот же код два раза

2023-01-30 12:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/exception/BookingNotFoundException.java
> +public class BookingNotFoundException extends Exception {
Так как `RuntimeException` -  непроверяемое исключение, пробрасывать его вверх по стеку или как-то специально обрабатывать не коде не требуется. Поэтому можно удалить все `throws`, где пробрасываются кастомые ошибки, которые наследуются от RuntimeException

2023-01-30 15:12 UTC, antbaranov commented
Спасибо за замечания. Они, как всегда ценные  👍

2023-01-31 12:57 UTC, AnastasiyaFomkina requested changes
Отметила все места, где нужно убрать throws из сигнатуры метода, так как необрабатываемые исключения прокидывать выше по стеку не нужно.
Чтобы упростить себе жизнь, лучше воспользоваться сочетанием клавиш
`Ctrl + Shift + F` для поиска по всему проекту:

<img width="1786" alt="Снимок экрана 2023-01-31 в 15 57 06" src="https://user-images.githubusercontent.com/43168217/215766015-d45392b5-ebfc-4109-b428-8dbfb8f4503a.png">

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    ) throws UserNotFoundException, ItemNotFoundException, InvalidDateTimeException, NotAvailableException {
Так как все типы приведенных здесь ошибок являются теперь непроверяемыми, обрабатывать их больше ненужно. Нужно удалить строку с throws. Ниже обозначу все места где нужно удалить, как "Удалить блок throws"

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    ) throws UserNotFoundException, BookingNotFoundException, InvalidStatusException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    ) throws UserNotFoundException, BookingNotFoundException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    ) throws UserNotFoundException, InvalidStatusException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    ) throws UserNotFoundException, InvalidStatusException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public ItemDto create(Long userId, ItemDto itemDto) throws UserNotFoundException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throws ItemNotFoundException, UserNotFoundException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public ItemDto get(Long userId, Long itemId) throws ItemNotFoundException, UserNotFoundException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public List<ItemDto> get(Long userId) throws UserNotFoundException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public List<ItemDto> search(Long userId, String text) throws UserNotFoundException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public UserDto create(@Valid @RequestBody UserDto userDto) throws ValidationException, DuplicateEmailException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    ) throws UserNotFoundException, ValidationException, DuplicateEmailException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public UserDto get(@PathVariable Long userId) throws UserNotFoundException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    UserDto create(UserDto userDto) throws ValidationException, DuplicateEmailException;
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    UserDto update(Long userId, UserDto userDto) throws UserNotFoundException, ValidationException, DuplicateEmailException;
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    UserDto get(Long userId) throws UserNotFoundException;
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/dto/State.java
> +    public static State validateState(String value) throws InvalidStatusException  {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    ) throws UserNotFoundException, ItemNotFoundException, NotAvailableException, InvalidDateTimeException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    ) throws BookingNotFoundException, UserNotFoundException, InvalidStatusException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public BookingInfoDto get(Long userId, Long bookingId) throws BookingNotFoundException, UserNotFoundException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public List<BookingInfoDto> get(Long userId, String value) throws UserNotFoundException, InvalidStatusException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public List<BookingInfoDto> getByOwner(Long userId, String value) throws UserNotFoundException, InvalidStatusException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    ItemDto create(Long userId, ItemDto itemDto) throws UserNotFoundException;
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    ItemDto update(Long userId, Long itemId, ItemDto itemDto) throws ItemNotFoundException, UserNotFoundException;
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    ItemDto get(Long userId, Long itemId) throws ItemNotFoundException, UserNotFoundException;
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    List<ItemDto> search(Long userId, String text) throws UserNotFoundException;
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    List<ItemDto> get(Long userId) throws UserNotFoundException;
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +            throws UserNotFoundException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +            throws ItemNotFoundException, UserNotFoundException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +            throws ItemNotFoundException, UserNotFoundException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +            throws UserNotFoundException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    ) throws UserNotFoundException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    ) throws UserNotFoundException, InvalidCommentException, ItemNotFoundException {
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    BookingInfoDto create(Long userId, BookingDto bookingDto) throws UserNotFoundException, ItemNotFoundException, NotAvailableException, InvalidDateTimeException;
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    BookingInfoDto approve(Long userId, Long bookingId, Boolean approved) throws BookingNotFoundException, UserNotFoundException, InvalidStatusException;
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    BookingInfoDto get(Long userId, Long bookingId) throws BookingNotFoundException, UserNotFoundException;
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<BookingInfoDto> get(Long userId, String state) throws UserNotFoundException, InvalidStatusException;
Удалить блок throws

2023-01-31 12:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<BookingInfoDto> getByOwner(Long userId, String state) throws UserNotFoundException, InvalidStatusException;
Удалить блок throws

2023-01-31 15:13 UTC, antbaranov commented on src/main/java/ru/practicum/shareit/booking/dto/State.java
> +    public static State validateState(String value) throws InvalidStatusException  {
без этого не проходит валидацию с выбросом ошибки

2023-01-31 15:31 UTC, AnastasiyaFomkina approved these changes
Осталось одно место, где пробрасывается throws. Работу принимаю, но прежде чем мерджить, удали, пожалуйста

2023-01-31 15:31 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/dto/State.java
> +    public static State validateState(String value) throws InvalidStatusException  {
Здесь нужно тоже удалить `throws` в сигнатуре метода, так как `InvalidStatusException` не требует того, чтобы его пробрасывали дальше

2023-02-09 10:23 UTC, merged