Add item requests
antbaranov/java-shareit pull request #3
Opened 2023-02-11 10:49 UTC by antbaranov

2023-02-13 12:13 UTC, AnastasiyaFomkina requested changes
Привет! 
Отличная работа, молодец 🔥
Оставила совсем немного комментариев

2023-02-13 12:13 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private final String userIdHeader = "X-Sharer-User-Id";
Можно вынести в качестве константы в отдельный утильный класс `Variables` и использовать не только в данном классе, но и во всех классах, где добавляется данный хэдер. Таким образом мы избежим дублирования

2023-02-13 12:13 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            @RequestParam(defaultValue = "10") Long size
Можно сразу ожидать от клиента `Pageable pageable`, так не придется настраивать основные поля для пагинации и добавлять новые, если потребуется

2023-02-13 12:13 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    // pagination
Лучше удалить подобные комментарии, они ничего не объясняют, а только путают

2023-02-13 12:13 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +@Mapper
При использовании `mapstruct` нужно только определить нужные нам методы и указать библиотеки поля с разными названиями, если это нужно. Реализовывать методы ненужно, так как библиотека их сама сгенерирует. Вот отличный [гайд](https://javarush.com/groups/posts/3698-chto-takoe-mapstruct-i-kak-praviljhno-nastroitjh-ego-dlja-moduljhnogo-testirovanija-v-springboo), где можно посмотреть, как его использовать

2023-02-13 12:13 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/requests/mapper/ItemRequestMapper.java
> +    /*ItemRequestDto toItemRequestDto(ItemRequest itemRequest);
Нужно удалять закомментированный код

2023-02-13 12:13 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryTest.java
> +    ItemRepository itemRepository;
Не хватает модификаторов доступа

2023-02-13 12:13 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/exception/DataExistExceptionTest.java
> +class DataExistExceptionTest {
Тесты на exception'ы лучше удалить, потому что это тесты ради тестов. Они ничего не проверяют, а только занимают место. Лучше проверять что какое-либо исключение было выброшено в нужный момент в юнит или интеграционных тестах сервисов

2023-02-13 15:42 UTC, antbaranov commented on src/test/java/ru/practicum/shareit/exception/DataExistExceptionTest.java
> +class DataExistExceptionTest {
Если убрать эти тесты, то проект не проходит тесты по покрытию на гитхабе
![Screen Shot 2023-02-13 at 18 35 04](https://user-images.githubusercontent.com/46896448/218503546-d51aa687-a423-44f1-a2b6-9b9bc2fb8adc.jpg)

2023-02-13 15:46 UTC, antbaranov commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +@Mapper
ПРобовал, не работает библиотека

2023-02-14 15:48 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/exception/DataExistExceptionTest.java
> +class DataExistExceptionTest {
Посмотрела внимательно, у тебя в коде используется только `PaginationException`, все остальные ты отлавливашь в хэндлере, но нигде не выбрасываешь. 
Нужно удалить все ошибки и тесты на них, так как они не нужны

2023-02-14 16:18 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +@Mapper
Прикладываю патч с примером работы с библиотекой. 
[Add_mapstruct_for_ItemRequest.patch](https://github.com/antbaranov/java-shareit/files/10734564/Add_mapstruct_for_ItemRequest.patch)

Чтобы использовать патч  нужно добавить его в корень проекта, нажать на нем правой кнопкой мыши и выбрать опцию `ApplyPatch`, в следубщем окне убедиться, что все файлы выбраны и нажать Ok
<img width="961" alt="Снимок экрана 2023-02-14 в 19 16 50" src="https://user-images.githubusercontent.com/43168217/218795237-5c37923e-ee79-4bd1-9941-876bd48ab9a0.png">
<img width="693" alt="Снимок экрана 2023-02-14 в 19 16 59" src="https://user-images.githubusercontent.com/43168217/218795244-8e82bc92-77f7-4219-bf40-cd66110c0c41.png">

Вот еще несколько статей про mapstruct:
https://www.baeldung.com/mapstruct
https://mapstruct.org/
https://javarush.com/groups/posts/3698-chto-takoe-mapstruct-i-kak-praviljhno-nastroitjh-ego-dlja-moduljhnogo-testirovanija-v-springboo

2023-02-14 16:28 UTC, AnastasiyaFomkina requested changes
Давай добьем проблему с exceptions и mapstruct.
В комментариях приложила патч с примером работы библиотеки на `ItemRequestMapper`, попробуй сделать аналогично в других мапперах

2023-02-14 16:28 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
>      static User matchUser(UserDto userDto, User user) {
Нужно сделать `default`, чтобы был доступ как и у других методов выше. `Static` нужно удалить

2023-02-14 16:28 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/DuplicateEmailException.java
>  public class DuplicateEmailException extends RuntimeException {
Нужно еще раз пройтись по всем ошибкам, посмотреть, что они нигде не используются и удалить. 
Проверить, что они нигде не используются можно просто, если использовать сочетание клавиш
 `crtl+ B`
<img width="1133" alt="Снимок экрана 2023-02-14 в 19 27 34" src="https://user-images.githubusercontent.com/43168217/218797801-d35a4e05-4e8d-4898-bb3f-c473a55daeaf.png">
Если данный класс не используется нигде, кроме тестов и хэндлера, то эти исключения больше не нужны и их надо удалить

2023-02-14 16:34 UTC, antbaranov commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            @RequestParam(defaultValue = "10") Long size
Не проходят тесты тогда

2023-02-14 17:46 UTC, antbaranov commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
>      static User matchUser(UserDto userDto, User user) {
Здесь по-другому не работает, mapper выдает ошибку. ТОлько так проходят тесты

2023-02-15 14:18 UTC, AnastasiyaFomkina requested changes
Случилась небольшая путаница с ErrorResponse, давай поправим

2023-02-15 14:18 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/exception/PaginationExceptionTest.java
> +        PaginationException paginationException = new PaginationException("test");
Нужно удалить тест ради покрытия

2023-02-15 14:18 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse2.java
> +public class ErrorResponse2 {
Нужно оставить один `ErrorResponse` с двумя полями `error` и `description`. В нем нужно добавить второй конструктор, только с полем `error`:
``` 
public ErrorResponse(String error){
      this.error = error;
}
```
Данный `ErrorResponse` нужно будет удалить

2023-02-15 14:18 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/PaginationException.java
> +    public static class ErrorResponse {
Нужно удалить дубль, а вместо него использовать `ru.practicum.shareit.exception.ErrorResponse `

2023-02-15 14:18 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/ErrorHandlerPagination.java
> +public class ErrorHandlerPagination {
Дубль класса `ErrorHandler`, нужно удалить

2023-02-15 14:18 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/utility/Variables.java
> +    public static final String userIdHeader = "X-Sharer-User-Id";
Так как это константа, нужно поправить именование в `CAMEL_CASE`

2023-02-15 14:18 UTC, AnastasiyaFomkina commented on src/main/resources/application.properties
> +spring.datasource.password=root
Нужно удалить старые параметры для h2

2023-02-15 15:12 UTC, antbaranov commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse2.java
> +public class ErrorResponse2 {
Это был рабочий вариант
На проверку отправлял с одним
Остался только в тестах

2023-02-15 15:23 UTC, antbaranov commented on src/main/java/ru/practicum/shareit/utility/Variables.java
> +    public static final String userIdHeader = "X-Sharer-User-Id";
У меня было в формате CAMEL_CASE
Но тесты на гитхабе стали строгие и такой формат не пропускают, пришлось переделать camelCase

2023-02-15 16:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
>      static User matchUser(UserDto userDto, User user) {
Какую конкретно ошибку получаешь?

2023-02-15 16:53 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/utility/Variables.java
> +    public static final String userIdHeader = "X-Sharer-User-Id";
Скинь, пожалуйста, коммит, где ты менял на CAMEL_CASE

2023-02-15 16:59 UTC, AnastasiyaFomkina requested changes
Задала вопросы в комментариях насчет ошибок, скинь, пожалуйста, примеры ответом здесь или в пачку, попробуем разобраться вместе

2023-02-15 16:59 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/ErrorHandlerPagination.java
> +public class ErrorHandlerPagination {
Нужно удалить этот ErrorHandler, он лишний и дублирует класс выше

2023-02-15 16:59 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +    public ErrorResponse(String error, String descriptions) {
Как оказалось description, нигде не используется, можно оставить одно поле и один конструктор

2023-02-16 02:03 UTC, antbaranov commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +    public ErrorResponse(String error, String descriptions) {
Да, верно, у меня было одно поле. Но было указано, что нужно создать второе поле и второй коструктор.

2023-02-16 02:11 UTC, antbaranov commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
>      static User matchUser(UserDto userDto, User user) {
@Mapping(target = "id", source = "userDto.id")
    @Mapping(target = "name", source = "userDto.name")
    @Mapping(target = "email", source = "userDto.email")
    User matchUser(UserDto userDto, User user);
    
    ОШибки в Postman тестах

2023-02-16 02:20 UTC, antbaranov commented on src/main/java/ru/practicum/shareit/utility/Variables.java
> +    public static final String userIdHeader = "X-Sharer-User-Id";
У меня изначально в проекте было CAMEL_CASE вот из майна 
[CAMEL_CASE](https://github.com/antbaranov/java-shareit/blob/main/src/main/java/ru/practicum/shareit/item/controller/ItemController.java)

2023-02-16 02:25 UTC, antbaranov commented on src/main/java/ru/practicum/shareit/utility/Variables.java
> +    public static final String userIdHeader = "X-Sharer-User-Id";
https://github.com/antbaranov/java-shareit/actions/runs/4154357748/jobs/7186693683

2023-02-16 02:34 UTC, antbaranov commented on src/main/java/ru/practicum/shareit/exception/ErrorHandlerPagination.java
> +public class ErrorHandlerPagination {
готово

2023-02-16 15:16 UTC, AnastasiyaFomkina approved these changes
Перед тем как мерджить изменения, удали, пожалуйста файл с патчем

2023-02-16 15:16 UTC, AnastasiyaFomkina commented on Add_mapstruct_for_ItemRequest.patch
> ++++ b/src/test/java/ru/practicum/shareit/requests/ItemRequestServiceImplTest.java	(date 1676390963044)
Перед тем как мерджить изменения, удали, пожалуйста файл с патчем

2023-02-24 07:23 UTC, merged